services:
  - type: web
    name: coinflip-duel-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production